In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
a=np.array([10,20,30])
print(type(a))

<class 'numpy.ndarray'>


In [11]:
a=np.array([[10,20,30],[50,55,40]])
print(type(a))
print(a.ndim)

<class 'numpy.ndarray'>
2


In [8]:
a=[10,20,52]
b=np.array(a)

In [12]:
details=[10,20,30,40,50]
sales=np.array(details)
print(sales)

[10 20 30 40 50]


In [17]:
a=[10,20,5,24,52]
arr=np.array(a)
print(arr[0])
print(arr[: :])
print(arr[:2])

10
[10 20  5 24 52]
[10 20]


In [27]:
a=[[5,8,9,8],
   [2,3,4,6]]
arr=np.array(a)
print(arr.ndim)
print(type(arr))
print(arr[1][2])

2
<class 'numpy.ndarray'>
4


In [22]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [23]:
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [28]:
details=[10,20,30,40,50]
sales=np.array(details)
print(sales)
print()
print(sales.T)

[10 20 30 40 50]

[10 20 30 40 50]


In [2]:
import numpy as np
details=[10,20,30,40,50]
sales=np.array(details)
print(sales)
print(max(sales))
print(min(sales))
print(sum(sales))


[10 20 30 40 50]
50
10
150


In [3]:
a=np.array([[45,54,66],[96,85,74]])
arr=np.array(a)
print(a)
print(arr.shape)
print(arr.T)


[[45 54 66]
 [96 85 74]]
(2, 3)
[[45 96]
 [54 85]
 [66 74]]


In [4]:
print(arr.reshape(3,2))

[[45 54]
 [66 96]
 [85 74]]


In [5]:
print(arr.reshape(1,6))
print(arr.ndim)

[[45 54 66 96 85 74]]
2


In [6]:
a=np.array([[45,54,0],[96,85,74]])
arr=np.array(a)
print(np.count_nonzero(arr))

5


In [7]:
print(np.sort(arr))

[[ 0 45 54]
 [74 85 96]]


In [8]:
print(np.sort(arr,axis=0))

[[45 54  0]
 [96 85 74]]


In [10]:
zeros=np.zeros((3,3))
print("\nZeros Array:\n",zeros)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
ones=np.ones((2,3))
print("\nOnes Array:\n",ones)


Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [43]:
import numpy as np
empt_arr=np.empty((2,3))
print("\nEmpty Array:\n",empt_arr)


Empty Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr_range=np.range((0,10,4))
print("\nArray With range:\n",arr_range)

taking multiple values as input,and returns the output in a single value =====================aggregrate functions
aggregate functions are:
    min
    max
    sum
    mean
    standard deviation
    product
    
   CONCATINATION:Adding of 2 values
   
   

In [37]:
import numpy as np
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4,-1)
mask = numbers % 4 == 0
filtered_value7s = numbers[mask]
print(filtered_values)

[ 8 12 16 20 24 28 32 36 40 44 48]


In [2]:
import numpy as np
x=[[2,3,4],
   [5,6,7],
   [8,9,0]] 
np.linalg.det(x)

29.99999999999999

In [3]:
matrix=np.array([[2,3,4],
                 [5,6,7],
                 [8,9,0]])
d=np.diagonal(matrix)
print(d)
print(np.trace(matrix))

[2 6 0]
8


In [4]:
A=np.array([[4,7],[2,6]])
A_inv=np.linalg.inv(A)
print(A_inv)
print(A_inv @ A)
print(A @ A_inv)

[[ 0.6 -0.7]
 [-0.2  0.4]]
[[1.0000000e+00 8.8817842e-16]
 [0.0000000e+00 1.0000000e+00]]
[[1. 0.]
 [0. 1.]]


In [5]:
A=np.array([[4,7],[2,6]])
eig_values, eig_vectors = np.linalg.eig(A)
print('Eigenvalues:',eig_values)
print("EigenVectors",eig_vectors)

Eigenvalues: [1.12701665 8.87298335]
EigenVectors [[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]


In [6]:
A=np.array([[4,7],[2,6]])
B=np.array([8,19])
solution=np.linalg.solve(A,B)
print('solution:',solution)

solution: [-8.5  6. ]


In [7]:
v=np.array([3, 4])
norm_v = np.linalg.norm(v)
print(norm_v)

5.0


In [12]:
import pandas as pd

In [14]:
import numpy as np
arr=np.array([10,15,18,22])
s=pd.Series(arr)
print(s)

0    10
1    15
2    18
3    22
dtype: int32


In [15]:
arr=np.array(['a','b','c','d'])
s=pd.Series(arr,
           index=['first','second','third','fourth'])
print(s)

first     a
second    b
third     c
fourth    d
dtype: object


In [22]:
s=pd.Series(50, index =[0,1,2,3,4])
print(s)

0    50
1    50
2    50
3    50
4    50
dtype: int64


In [27]:
d={'Name':"hardik","IPL":"MI","runs":1500}
s=pd.Series(d)
print(s)

Name    hardik
IPL         MI
runs      1500
dtype: object


In [ ]:
#MATHEMATICAL OPERATIONS IN SERIES

In [28]:
s=pd.Series([1,2,3,4,5])
print(s*2)

0     2
1     4
2     6
3     8
4    10
dtype: int64


In [29]:
print(s**2)

0     1
1     4
2     9
3    16
4    25
dtype: int64


In [30]:
 print(s[s>2])

2    3
3    4
4    5
dtype: int64


In [33]:
s1=pd.Series([1,2,3,4,5], index=[['a','b','c','d','e']])
s2=pd.Series([16,25,14,75,85], index=[['a','b','c','d','e']])
s3=pd.Series([13,58,96,47,25], index=[['a','b','c','d','e']])
print(s1+s2)
print(s1+s3)
print(s2+s3)
print(s2.add(s3,fill_value=0))

a    17
b    27
c    17
d    79
e    90
dtype: int64
a    14
b    60
c    99
d    51
e    30
dtype: int64
a     29
b     83
c    110
d    122
e    110
dtype: int64
a     29
b     83
c    110
d    122
e    110
dtype: int64


In [44]:
import pandas as pd
import numpy as np
arr=np.array([45,54,58,96,85,74])
s=pd.Series(arr)
print(s)
print(s.head(3))
print(s.tail(2))

0    45
1    54
2    58
3    96
4    85
5    74
dtype: int32
0    45
1    54
2    58
dtype: int32
4    85
5    74
dtype: int32


In [37]:
import pandas as pd
import numpy as np
arr=np.array([45,54,58,96,85,74])
s=pd.Series(arr)
print(s)
print(s.loc[:2])   #loc is used for the location based upon the value.........nd it is excluded
print(s.loc[3:4])
s.loc[2:3]

0    45
1    54
2    58
3    96
4    85
5    74
dtype: int32
0    45
1    54
2    58
dtype: int32
3    96
4    85
dtype: int32


2    58
3    96
dtype: int32

In [40]:
import pandas as pd
import numpy as np
arr=np.array([45,54,58,96,85,74])
s=pd.Series(arr)
print(s.iloc[:2])   #loc is used for the location based upon the value.........nd it is excluded
print(s.iloc[3:4])
s.iloc[2:3]

0    45
1    54
dtype: int32
3    96
dtype: int32


2    58
dtype: int32

In [41]:
import pandas as pd
import numpy as np
arr=np.array([45,54,58,96,85,74])
s=pd.Series(arr)
print(s)
print(s.index)

0    45
1    54
2    58
3    96
4    85
5    74
dtype: int32
RangeIndex(start=0, stop=6, step=1)


In [ ]:
#*****************DATA FRAME************************